use version.py get_version to get version (#18563)
A prior commit introduced checking for the version of a node related to move to log4j2 but it was causing an error
AttributeError("'ClusterNode' object has no attribute 'version'") This PR uses the get_version method from version.py which checks if the Node has a version attribute preventing an error.

Reviewers: Matthias Sax <mjsax@apache.org>